# Generated by Django 6.0 on 2026-06-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agenda_color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
