# Generated by Django 6.0 on 2026-03-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(default='+56 9 1234 5678', max_length=20, verbose_name='Teléfono Móvil')),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Fijo')),
                ('email', models.EmailField(default='contacto@atilaclinic.cl', max_length=254, verbose_name='Email de Contacto')),
                ('direccion', models.CharField(default='Av. Principal 123, Vitacura, Santiago', max_length=255, verbose_name='Dirección Principal')),
                ('url_facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL Facebook')),
                ('url_instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL Instagram')),
                ('url_whatsapp', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL WhatsApp')),
                ('google_maps_embed_url', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3330.7267890123456!2d-70.5956789!3d-33.3904874!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzPCsDIzJzI1LjgiUyA3MMKwMzUnNDQuNCJX!5e0!3m2!1ses!2scl!4v1234567890123!5m2!1ses!2scl', help_text='URL del iframe de Google Maps', verbose_name='URL del Mapa de Google')),
                ('google_maps_link', models.URLField(default='https://www.google.com/maps/search/?api=1&query=Av.+Principal+123,+Vitacura,+Santiago', help_text='URL para abrir en Google Maps', verbose_name='Link de Google Maps')),
                ('horario_semana', models.CharField(default='Lunes a Viernes: 8:00 - 20:00', max_length=100, verbose_name='Horario Semana')),
                ('horario_sabado', models.CharField(default='Sábados: 9:00 - 14:00', max_length=100, verbose_name='Horario Sábado')),
                ('horario_domingo', models.CharField(default='Domingos cerrado', max_length=100, verbose_name='Horario Domingo')),
                ('info_estacionamiento', models.CharField(default='Estacionamiento gratuito', max_length=100, verbose_name='Info Estacionamiento')),
                ('info_transporte', models.TextField(default='Metro: Línea 1, Estación Vitacura\nBus: Líneas 412, 413, 425', verbose_name='Info Transporte Público')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
                'db_table': 'configuracion',
            },
        ),
    ]
